// 1) Create function sum that receives an array as parameter and return the sum of the elements (only numerical ones)

let paramsOne = [ 10, 20, 30, 40]
let result = 0
function sum(){
    for(let i=0; i < 4; i++){
        result+=paramsOne[i]
    }
    return result
}

// 2) Create function min that receives an array and returns the minumum value in the array

let paramsTwo = [23, 45, 22, 13]
let minimum = myarray[0]
        function min(){
            for (let i = 0; i<myarray.length; i++)
            {
                if(minimum>myarray[i])
                {minimum=myarray[i]}
            }
    return minimum
       }

// 3) Create function arrayFi that receives an object and trasforms it in an array.
//    Example: arrayFi({ name: "John", surname: "Doe"}) returns [ "name", "john", "surname", "Doe"]


// 4) Create function objectyFi that revert the array generated by arrayFi into and object


// 5) Create function revertArray that revert the elements into an array


// 6) Create function swappy that receives 2 positions and swap them into the array.
//    Example: array = [ 1, 2, 3, 4]. Swappy(0, 3) ==> [3, 2, 1, 4]

let myarray=[23, 45, 22, 13]
let minimum= myarray[0]
        function min(){
            for (let i=0; i<myarray.length; i++)
            {
                if(minimum>myarray[i])
                {minimum=myarray[i]}
            }
    return minimum
       }
   
let person={
    name: "John",
    surname:"Doe"
}

let mysecondarray=[]
function arrayFi(){
      mysecondarray.push(person.name)
      mysecondarray.push(person.surname)     
      console.log(mysecondarray)   
}


function objectyFi(){
   mysecondarray.pop= person.name
   mysecondarray.pop=person.surname
    console.log(person)
}

let fruits=["apple", "grape", "orange", "watermelon"]
	let j=fruits.length-1;  
	let i=0;   
	function revert(){
    while(i<j)
	{
		temp=fruits[i];
		fruits[i]=fruits[j];
		fruits[j]=temp;
		i++;
		j--;
	}
    console.log(fruits)
    }

let temp=0
let arrayswap=[1, 2, 3, 4]
function swappy(num1, num2)
{
    temp=arrayswap[num1]
    arrayswap[num1]=arrayswap[num2]
    arrayswap[num2]=temp
    console.log(arrayswap)
}